# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 19:06
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', blog.models.UUIDField(blank=True, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
                ('auth', models.BooleanField()),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
    ]
