# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 19:59
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20160317_1509'), ('blog', '0003_auto_20160318_0016'), ('blog', '0004_auto_20160318_1943'), ('blog', '0005_auto_20160318_1944'), ('blog', '0006_auto_20160318_2139'), ('blog', '0007_post_tags')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', blog.models.UUIDField(blank=True, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
                ('auth', models.BooleanField()),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to=b'blog.Tag'),
        ),
    ]
