# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 19:09
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=blog.models.UUIDField(blank=True, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
