# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.CharField(default=b'54c31feedb3d11e5af930021cc711042', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(default=b'54be6500db3d11e5aba60021cc711042', max_length=32, primary_key=True, serialize=False),
        ),
    ]
