# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160224_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.CharField(default=b'b03845b2b6e54d49891f00320a334d1c', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(default=b'4df3593d79b147029560e3be16646851', max_length=32, primary_key=True, serialize=False),
        ),
    ]
