# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160318_0016'),
    ]

