# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160224_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.CharField(default=b'ee9faf9c5db04420b1e3b862111cd3af', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(default=b'2fad7fa8f50b43b78b81b950ac0be7be', max_length=32, primary_key=True, serialize=False),
        ),
    ]
