# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160318_1943'),
    ]

    operations = [

    ]
