# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160224_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.CharField(default=b'7c4a06bf4327424aa43f2d806530cadf', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(default=b'4002c4f93ce548bda71a3c5c24118ae1', max_length=32, primary_key=True, serialize=False),
        ),
    ]
