# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:49
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160224_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=blog.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=blog.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
