# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:35
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160224_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmpPost',
            fields=[
                ('postid', blog.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tmpTags',
            fields=[
                ('tagid', blog.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='tmppost',
            name='tags',
            field=models.ManyToManyField(to='blog.tmpTags'),
        ),
    ]
