# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:54
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160227_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', blog.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
