# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160227_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted']},
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(null=True, to='blog.Tag'),
        ),
    ]
