# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
