# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsglobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('jumbo', models.BooleanField(default=False)),
                ('jumbo_img', models.CharField(max_length=200)),
                ('jumbo_url', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsglobal.Site')),
            ],
        ),
    ]
