# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsglobal', '0002_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='jumbo_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='jumbo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
