# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsglobal', '0003_auto_20160315_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='jumbo',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='jumbo_img',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='jumbo_url',
        ),
    ]
