# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsglobal', '0005_auto_20160316_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wsglobal.Site'),
        ),
    ]
