# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsglobal', '0006_auto_20160316_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='link',
        ),
    ]
