# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsglobal', '0007_remove_siteinfo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
