# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 05:22
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', blog.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('weight', models.IntegerField()),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.Menu')),
            ],
        ),
    ]
