# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('navigation', '0001_initial'), ('navigation', '0002_auto_20160316_1054'), ('navigation', '0003_auto_20160316_2340')]

    initial = True

    dependencies = [
        ('wsglobal', '0001_squashed_0010_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wsglobal.Site')),
            ],
        ),
        migrations.CreateModel(
            name='NavItemNested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(default='#', max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.NavItem')),
            ],
        ),
    ]
