# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wsglobal', '0006_auto_20160316_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wsglobal.Site')),
            ],
        ),
    ]
