# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=32)),
                ('baseurl', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.SiteNav'),
        ),
    ]
