# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItemNested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='navitem',
            old_name='show',
            new_name='visible',
        ),
        migrations.AddField(
            model_name='navitemnested',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.NavItem'),
        ),
    ]
