# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20160316_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
