# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20160305_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
    ]
