# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default=b'#', max_length=200),
        ),
    ]
